app/models.py
from app import db

class Listing(db.Model):
    __tablename__ = 'listing'
    id = db.Column(db.Integer, primary_key=True)
    year = db.Column(db.Integer)
    week_number = db.Column(db.Integer)
    artist = db.Column(db.String)
    title = db.Column(db.String)
    spotify_url = db.Column(db.String)
    spotify_id = db.Column(db.String)
    image = db.Column(db.String)

app/blueprints/main/forms.py
from flask.ext.wtf import Form
from wtforms import BooleanField, SubmitField


class UpdateForm(Form):
    confirm = BooleanField('confirm')
    submit = SubmitField()

app/__init__.py
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.bootstrap import Bootstrap
from config import config


bootstrap = Bootstrap()

db = SQLAlchemy()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    db.init_app(app)
    from app.blueprints.main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    bootstrap.init_app(app)
    return app

app/blueprints/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views, forms #let's import the views and forms into here too

app/blueprints/main/views.py
from flask import render_template, redirect, url_for, flash
from . import main
from app import db
from app.models import Listing
from .forms import UpdateForm
from app.libs import topp

@main.route('/')
def home():
    return render_template('index.html')

@main.route('/update', methods=['GET', 'POST'])
def update():
	form = UpdateForm()
	if form.validate_on_submit():
		if form.confirm.data is False:
			flash('Check the confirm box!')
			return redirect(url_for('main.update'))
		topp.update_database()
		return redirect(url_for('main.home'))
	return render_template('update.html', form=form)

@main.route('/results')
def results():
	listings = Listing.query.all()
	return render_template('results.html', listings=listings)

app/templates/base.html
{% extends 'bootstrap/base.html' %}
​
{% block title %}My Flask App{% endblock %}
​
{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}
​
{% block navbar %}
<style>
    .navbar-brand {
        padding: 2px;
    }
</style>
<div class="navbar navbar" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.home') }}"><img alt="MyFlaskApp" height=45px src="/static/logo.png"/></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.home') }}">Home</a></li>
                <li><a href="{{ url_for('main.update') }}">Update</a></li>
                <li><a href="{{ url_for('main.results') }}">Results</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Dropdown <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#"># 1</a></li>
                        <li><a href="#"># 2</a></li>
                        <li><a href="#"># 3</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}
​
{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
​
    {% block page_content %}{% endblock %}
</div>
{% endblock %}
​
{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Front page{% endblock %}

{% block page_content %}

<!-- Form that the user fills out. When the user has submitted the form, he will be redirected to the page results.html where the submitted info will be matched with the info in the database -->

<h1> Fill in form to find the toplist song for that date </h1>

<form class="form-horizontal">
<fieldset>

<!-- Select Basic -->
<div class="form-group">
  <label class="col-md-4 control-label" for="aar">Choose birth year</label>
  <div class="col-md-4">
    <select id="year" name="year" class="form-control">
      <option value="">1988</option>
      <option value="">1987</option>
      <option value="">1986</option>
    </select>
  </div>
</div>


<div class="form-group">
  <label class="col-md-4 control-label" for="maaned">Choose birth month</label>
  <div class="col-md-4">
    <select id="month" name="month" class="form-control">
      <option value="">Jan</option>
      <option value="">Feb</option>
      <option value="">Mars</option>
    </select>
  </div>
</div>

<!-- Note, I actually want to use day here. But the info scraped is in weeks. So I need to figure out how to convert the info day/month/year into week number. I found a javascript for it. But for now we can just keep it simple and just use weeks. -->
<div class="form-group">
  <label class="col-md-4 control-label" for="dag">Choose birth day</label>
  <div class="col-md-4">
    <select id="week" name="week" class="form-control">
      <option value="">02</option>
      <option value="">03</option>
      <option value="">04</option>
    </select>
  </div>
</div>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label" for="send"></label>
  <div class="col-md-4">
    <button id="send" name="send" class="btn btn-primary">Find song!</button>
  </div>
</div>

</fieldset>
</form>

{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/result.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Result{% endblock %}

{% block page_content %}





<!-- For each user input this ID will be replaced with list.SpotID, to generate a play button from spotify for that specific song. -->
<iframe src="https://embed.spotify.com/?uri=spotify:track:4HDrxZzuL7mQ6qQZFRpw1s" frameborder="0" allowtransparency="true"></iframe>






<!-- Just an example connection to database. I guess I somehow need to compare list.Year and so on with user input? -->
<!-- Each result from the user submit should show title of song, artist, year, week and an image.  -->
{% for lists in listing %}
  


  <strong>Year:</strong> {{ lists.Year }} <br>
  <strong>Week:</strong> {{ lists.Week }} <br>
  <strong>Artist:</strong> {{ lists.Artist }} <br>
  <strong>Title:</strong> {{ lists.Title }} <br>
  <strong>SpotifyURL:</strong> {{ lists.SpotUrl }} <br>
  <strong>SpotifyID:</strong> {{ lists.SpotID }} <br>
  <strong>Image:</strong> {{ lists.Image }} <br>





{% endfor %}

{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/results.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
​
{% block title %}Result{% endblock %}
​
{% block page_content %}
​

​
<!-- Just an example connection to database. I guess I somehow need to compare list.Year and so on with user input? -->
<!-- Each result from the user submit should show title of song, artist, year, week and an image.  -->
{% for lists in listings %}
<table class="table">
	<tr>
		<th>Year</th>
		<td>{{ lists.year }}</td>
	</tr>
	<tr>
		<th>Week</th>
		<td>{{ lists.week_number }}</td>
	</tr>
	<tr>
		<th>Artist</th>
		<td>{{ lists.artist }}</td>
	</tr>
	<tr>
		<th>Title</th>
		<td>{{ lists.title }}</td>
	</tr>
	
	<tr>
		<th>Spotify ID</th>
		<td><iframe src="{{ lists.spotify_id }}" frameborder="0" allowtransparency="true"></iframe></td>
	</tr>
	
</table>
​
{% endfor %}
​
{% endblock %}
​
{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/update.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Update{% endblock %}

{% block page_content %}

{{ wtf.quick_form(form) }}

{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}